name: TogglePickups
version: 1.0
main: me.joshuaemq.TogglePickupsPlugin
author: joshuaemq
description: Allows you to toggle pickups!

commands:
     toggledrops:
         usage: /<command>
         aliases: [td]
         description: Toggle Drops